require: rubocop-rails

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/**/*
    - test/**/*
    - vendor/bundle/**/*
    - config.ru
    - Gemfile
    - Rakefile
